// Generated by LiveScript 1.2.0
var Beat;
Beat = (function(){
  Beat.displayName = 'Beat';
  var prototype = Beat.prototype, constructor = Beat;
  function Beat(num){
    this.num = num;
  }
  prototype.dur = function(game){
    return 60 * this.num / game.level.bpm;
  };
  prototype.toTime = function(game){
    return state.timeStartLevel + this.dur(game);
  };
  prototype.add = function(beat){
    return new Beat(this.num + beat.num);
  };
  prototype.inc = function(){
    this.num += 1;
    return this;
  };
  return Beat;
}());