// Generated by LiveScript 1.2.0
var Character;
Character = (function(){
  Character.displayName = 'Character';
  var prototype = Character.prototype, constructor = Character;
  function Character(x, y){
    this.x = x;
    this.y = y;
    this.up();
    this.pulse();
  }
  prototype.pulseMag = 10;
  prototype.hitDur = 0.2;
  prototype.isHitting = false;
  prototype.lastPulse = 0;
  prototype.down = function(){
    return this.state = "down";
  };
  prototype.up = function(){
    return this.state = "up";
  };
  prototype.hit = function(){
    this.down();
    return this.isHitting = true;
  };
  prototype.pulse = function(){
    return this.headY = this.y + this.pulseMag;
  };
  prototype.animUpdate = function(){
    var speed;
    if (this.isHitting && game.level.audio.getTime() > this.lastPulse + this.hitDur) {
      this.up();
    }
    speed = this.pulseMag / game.level.beatDur;
    return this.headY = this.headY - speed * game.delta * 1000;
  };
  prototype.draw = function(ctx, sdata){
    var sUp, sDown, sHead, s, x;
    sUp = sdata.frames['raised.png'].frame;
    sDown = sdata.frames['lowered.png'].frame;
    sHead = sdata.frames['head.png'].frame;
    if (this.state === "down") {
      s = sDown;
    } else {
      s = sUp;
    }
    x = this.x - s.w / 2;
    ctx.drawImage(sprites, s.x, s.y - 10, s.w, s.h, x, this.y, s.w, s.h);
    return ctx.drawImage(sprites, sHead.x, sHead.y, sHead.w, sHead.h, x, this.headY, sHead.w, sHead.h);
  };
  return Character;
}());