// Generated by LiveScript 1.2.0
var Character;
Character = (function(){
  Character.displayName = 'Character';
  var prototype = Character.prototype, constructor = Character;
  function Character(x, y){
    this.x = x;
    this.y = y;
    this.pulse();
    this.state = 'relaxed';
    this.frame = '0.png';
  }
  prototype.pulseMag = 10;
  prototype.hitDur = 0.2;
  prototype.lastPulse = 0;
  prototype.hit = function(){
    this.state = 'hitting';
    this.animStart = state.now;
    this.animIndex = 0;
    return this.animTime = 0;
  };
  prototype.pulse = function(){
    return this.headY = this.y + this.pulseMag + 4;
  };
  prototype.animUpdate = function(){
    var speed;
    speed = this.pulseMag / 1000;
    if (this.state === 'hitting' && this.animIndex < animations.hitting.length) {
      this.frame = animations.hitting[this.animIndex];
      this.animTime += state.delta;
      if (this.animTime >= 1 / 24) {
        this.animIndex += 1;
        this.animTime = 0;
      }
    }
    if (!state.done) {
      return this.headY = this.headY - speed * state.delta * 1000;
    }
  };
  prototype.draw = function(ctx, sdata){
    var sHead, s, x;
    sHead = sdata.frames['drummer/head.png'].frame;
    s = sdata.frames["drummer/" + this.frame].frame;
    x = this.x - s.w / 2;
    ctx.drawImage(sprites, s.x, s.y - 10, s.w, s.h, x, this.y, s.w, s.h);
    return ctx.drawImage(sprites, sHead.x, sHead.y, sHead.w, sHead.h, x, this.headY, sHead.w, sHead.h);
  };
  return Character;
}());