// Generated by LiveScript 1.2.0
var Notif;
Notif = (function(){
  Notif.displayName = 'Notif';
  var prototype = Notif.prototype, constructor = Notif;
  function Notif(target, message){
    this.target = target;
    this.message = message;
    this.x = this.target.x;
    this.y = this.target.y;
    this.lifespan = 2;
    this.notifAge = 0;
    this.notifDelay = 0.25;
    this.animNotifs = [];
    this.age = 0;
    this.speed = 80;
  }
  prototype.percentAge = function(){
    return (this.lifespan - this.age) / this.lifespan;
  };
  prototype.animUpdate = function(){
    this.age += state.delta;
    this.y -= this.speed * state.delta;
    this.speed -= 1;
    return this;
  };
  prototype.reset = function(){
    this.x = this.target.x;
    this.y = this.target.y;
    this.age = 0;
    return this.speed = 40;
  };
  prototype.draw = function(ctx){
    ctx.fillStyle = "white";
    ctx.textAlign = "left";
    ctx.textBaseline = "top";
    ctx.font = "24px 'Action Man'";
    return ctx.fillText(this.message, this.x, this.y - 20);
  };
  return Notif;
}());