// Generated by LiveScript 1.2.0
var Notif;
Notif = (function(){
  Notif.displayName = 'Notif';
  var prototype = Notif.prototype, constructor = Notif;
  function Notif(target, message){
    this.target = target;
    this.message = message;
    this.x = this.target.x;
    this.y = this.target.y;
    this.lifespan = 2;
    this.notifAge = 0;
    this.notifDelay = 0.25;
    this.animNotifs = [];
    this.age = 0;
    this.speed = 80;
    this.scale = 0;
    this.opacity = 1;
  }
  prototype.percentAge = function(){
    return (this.lifespan - this.age) / this.lifespan;
  };
  prototype.animUpdate = function(){
    var maxScale, critAge;
    this.age += state.delta;
    maxScale = 1.1;
    critAge = 0.5 - Math.asin(1 / maxScale) / (2 * Math.PI);
    if (this.age <= critAge) {
      this.scale = 1.1 * Math.sin(this.age * 2 * Math.PI);
      return this.opacity = 1;
    } else {
      this.scale = 1;
      return this.opacity = (this.lifespan - this.age) / critAge;
    }
  };
  prototype.reset = function(){
    this.x = this.target.x;
    this.y = this.target.y;
    this.age = 0;
    return this.speed = 40;
  };
  prototype.draw = function(ctx, sdata){
    var b, h, w;
    b = sdata.frames["balloon.png"].frame;
    ctx.globalAlpha = this.opacity;
    h = b.h * this.scale * 0.5;
    w = b.w * this.scale * 0.5;
    ctx.drawImage(sprites, b.x, b.y, b.w, b.h, this.x - h / 2, this.y - w / 2 + 20, w, h);
    ctx.fillStyle = "#6a6868";
    ctx.textAlign = "center";
    ctx.textBaseline = "top";
    ctx.font = "24px 'Action Man'";
    ctx.fillText(this.message, this.x, this.y - 10);
    return ctx.globalAlpha = 1;
  };
  return Notif;
}());