// Generated by LiveScript 1.2.0
var ref$, minimum, head, find, sortBy, flatten, filter, map, reject, each, fold, zip, min, max, settings, sprites, ui;
ref$ = require('prelude-ls'), minimum = ref$.minimum, head = ref$.head, find = ref$.find, sortBy = ref$.sortBy, flatten = ref$.flatten, filter = ref$.filter, map = ref$.map, reject = ref$.reject, each = ref$.each, fold = ref$.fold, zip = ref$.zip, min = ref$.min, max = ref$.max;
settings = {
  screenW: 960,
  screenH: 640,
  laneW: 960 / 9,
  margin: 960 / 9,
  startline: 342,
  finishline: 612,
  speed: 50,
  keys: {
    83: 's',
    68: 'd',
    70: 'f',
    32: 'space',
    74: 'j',
    75: 'k',
    76: 'l'
  },
  grade: function(t){
    switch (false) {
    case !(-0.100 <= t && t <= 0.100):
      return "great";
    case !(0.100 < t && t <= 0.500):
      return "good";
    case !(-0.100 > t && t >= -0.500):
      return "good";
    case !(t > 0.500 || t < -0.500):
      return "ignored";
    }
  },
  score: function(grade){
    switch (false) {
    case grade !== "great":
      return 150;
    case grade !== "good":
      return 50;
    case grade !== "bad":
      return -100;
    default:
      return 0;
    }
  }
};
sprites = new Image();
sprites.src = "/sprites/sprites.png";
ui = {
  buttons: {
    song1: new TextButton("Hold Me Steady", 144, 144, 'playSong')
  }
};